### ISSUE TITLE
1.12.2

### ISSUE THREAD

**Issue by 0jeff** [Mr-Pineapple/AdditionalGuns#20]

**Comment by Voider404** [comment]
never

**Comment by 0jeff** [comment]
90% of mods have 1.12.2 version so why not?

**Comment by Voider404** [comment]
Consider the fact that this addon started existing WAY after 1.12 lost the support, so, yeah.

**Comment by 0jeff** [comment]
1.12.2 is still most popular version and have support and crayfish gun mod also have 1.12.2 support so its not impossible

**Comment by 0jeff** [comment]
why close without reason? this is very bad of additional guns

**Comment by Autovw** [comment]
Sure, I can give you some reasons if you want: 1.12 is old and unsupported by Forge and both Mr. Pineapple and I no longer mod for it because of that. The 1.12 version of the Gun Mod is also discontinued and backporting would be a waste of our time. If you want to use 1.12 then that's up to you, but don't expect modders to support ancient versions.

Bear in mind that this is the **issue tracker**. This is not the place to ask for backports.

**Comment by 0jeff** [comment]
1.12.2 is best version and supported. all good modpacks are also 1.12.2 or older you can't deny that. its very bad of mister pineapple and autovv to think like this

**Comment by XviktorwoodX** [comment]
dude, you said yourself that 90% of mods are on 1.12.2, so why don't you find an alternate, huh?

**Comment by aemogie** [comment]
> 1.12.2 is best version
> all good modpacks

since when was github issues the place for opinions?

and what if 1.12 doesn't have the necessary features for the mod to work? the game has changed a lot in that period.

if you *really* want a backport, do it yourself. the mod is open source. go ahead. the source is right there in the `Code` tab. nobody is stopping you. nobody can.

**Comment by Mr-Pineapple** [comment]
The issues tab of a repository is to report issues with a version of the project, please refrain from posting anything else in here, especially asking to create older versions for unsupported game versions.
