### ISSUE TITLE
Guns Rendered Incorrectly When Main Hand Option is Set to Left

### ISSUE THREAD

**Issue by ThickPropheT** [Mr-Pineapple/AdditionalGuns#40]
![2022-06-14_23 25 29](https://user-images.githubusercontent.com/6137018/175836415-d534abbf-1f69-44b0-958e-9e966fc8a99d.png)

Guns seem to be culled incorrectly when held while `Skin Customization... > Main Hand` is set to `Left`.

Additionally, when playing SMP, if _ANY_ player has `Main Hand` set to `Left`, players will not be able to see each others' guns.

**Comment by CasualNoLifer** [comment]
Hello. I am _not_ one of the maintainers for this project but I am a contributor working on fixing this type of issue. The models used in this mod do not currently have a left hand offset identical to the right hand. One of my upcoming projects is to further fix the handheld properties for the guns and this is one of the issues I will be fixing along with fixing ADS angles. 

It is strange to me that the model is appearing at all because its .json file has it display completely offscreen when set in the left hand. The textures/model also appears to be negative rather than positive, giving it a see-through look. I'll do some testing and play around with it as it's possible that there is no left hand support to begin with for the base mod, Mr. Crayfish's Gun Mod. (I am new to the project and am not certain if there is or is not left-hand support.)

**Comment by ThickPropheT** [comment]
Thanks for the reply. If it turns out that the base mod also does not support this, I can submit a report there.

**Comment by Autovw** [comment]
To answer @CasualNoLifer :

> The models used in this mod do not currently have a left hand offset identical to the right hand.

This is always something I check for when new models are submitted, but it could be that some of the older models still have issues with this. (including the gun shown in the image)

> It is strange to me that the model is appearing at all because its .json file has it display completely offscreen when set in the left hand.

We prefer not setting the left hand value because 1. Minecraft will simply "mirror" the right hand position if the left hand is unset. 2. if we have to change the hand positions, we only have to do it once. 3. it simply saves a few lines of code :)

To answer @ThickPropheT :

> Additionally, when playing SMP, if ANY player has Main Hand set to Left, players will not be able to see each others' guns.

This sounds more like an issue with MrCrayfish's Gun Mod, but I'm currently unable to check this. Can you verify this by holding guns from MrCrayfish's Gun Mod instead?

**Comment by CasualNoLifer** [comment]
> Thanks for the reply. If it turns out that the base mod also does not support this, I can submit a report there.

All guns have been edited to work in the left hand now. The updated versions will appear in the next update. :)
