### ISSUE TITLE
None of the AKs, except for ak15 have a silenced sound.

### ISSUE THREAD

**Issue by Igggosha** [Mr-Pineapple/AdditionalGuns#65]
[no media provided]

**Comment by Igggosha** [comment]
ak105 also doesn't have any sounds

**Comment by Autovw** [comment]
Can confirm, some AK's still use the AK suppressed sound which got removed in 0.7.0. Not sure how we missed this in our testing.

**Comment by CasualNoLifer** [comment]
I'm going through the weapon data for the AKs right now to do some fixes then will submit a PR. I don't know how this got through testing because I specifically tested the silenced sounds for these guns. Something weird probably happened when we merged or an older version of the weapon data got added instead. Will be fixed momentarily.

**Comment by CasualNoLifer** [comment]
This has now been fixed and should appear in the next hotfix update. (This issue can be closed whenever)
