### ISSUE TITLE
Mod Development Suggestions

### ISSUE THREAD

**Issue by CasualNoLifer** [Mr-Pineapple/AdditionalGuns#69]
A brief catalogue of my own personal suggestions for the mod:

- Remove AK-104 (It's almost identical to the AKM Custom and uses exactly the same textures as the AKM Custom and AK74m)
- Distinguishable textures between AK-12 and AK-15
- AKS-74U and AK-74 texture color changes
- Distinguishable textures between AKM Custom and AK74m
- AKM Color changes
- FN2000 name correction to F2000 (The official name is FN F2000)
- AK74m name change to AK74 Custom to be consistent with AKM Custom
- Banshee remodel
- MAT-49 remodel
- Remove the stock from several models such as the AR15 platform guns (M16A2, M4A4, M4A1) and make them attachments
- M4A1s name correction to M4A1 (M4A1s is a CS:GO reference. The gun in this mod does not have a silencer on it so it's a normal M4A1. Changing the name would also make it less obvious that several of the guns are inspired from CS:GO and give the mod a more diverse feel)
- AKS-74U remove attachment slot and give it its signature stock, give it a muzzle booster and remove the muzzle slot

**Comment by Autovw** [comment]
I'll just quickly go over this.

> Remove AK-104

I think we should just keep it at this point. It's already in the mod anyway. Removing it entirely might hurt more than keeping it.

> Distinguishable textures between AK-12 and AK-15
AKS-74U and AK-74 texture color changes
Distinguishable textures between AKM Custom and AK74m
AKM Color changes

Between you and the author :)

> FN2000 name correction to F2000 (The official name is FN F2000)

Sure. I can just change the name in the translation file.

> AK74m name change to AK74 Custom to be consistent with AKM Custom

Not entirely sure, but we can change the name in the translation for this one too.

> Banshee remodel
MAT-49 remodel

Not a big fan of remodels, but we could consider it.

> Remove the stock from several models such as the AR15 platform guns (M16A2, M4A4, M4A1) and make them attachments

Not a bad idea (if the author is also okay with this). Though one attachment for all AR15's would be preferred in this case (if possible)

> M4A1s name correction to M4A1

If I can make sure this doesn't break compatibility with previous versions, sure.

> AKS-74U remove attachment slot and give it its signature stock, give it a muzzle booster and remove the muzzle slot

Probably no. This guns seems popular among users because it can have custom stocks. Removing that ability might upset some people.
