### ISSUE TITLE
Continous crashed caused from this mod

### ISSUE THREAD

**Issue by Carjanjan** [Mr-Pineapple/AdditionalGuns#97]
While I was playing and building an server with this mod installed on it , My game randomly crashed and from that moment it kept crashing and crashing , I checked the versions , I had the mods installed and for some reason it was only happening to me... I took a look at the crash report and it said that this mod required cgm 1.2.6 , I had it installed on the server and on my computer , anyone got any idea?

**Comment by Autovw** [comment]
Based on what you're describing it seems that you didn't install MrCrayfish's Gun Mod along with the mod. Make sure you have the same version of said mod on both the client and server side, otherwise the game will crash.

If this is already the case, and the client and/or server still crashes, please provide a crash log to the conversation :)

**Comment by Carjanjan** [comment]
I do have MrCrayfish`s Gun Mod along with this mod , I dont have much time now but ill provide the whole crash log if needed
